### ISSUE TITLE
its-control stops working after adding a dot.

### ISSUE THREAD

**Issue by thedrummeraki** [brandonbrule/its-framework#2]
**Expected behaviour**
Let's say we have two inputs:
```
<input its-control="1mxdmp">
<input its-control="1mxdmp">
```
Both inputs will share the same contents.

**What happens**
Once a dot is typed, the contents are not shared anymore accross inputs.

**Comment by brandonbrule** [comment]
Aweee yeah, I couldn't get this going right... until now!
